### PR TITLE
Remove scripts

### PR DESCRIPTION
**Pull request by dalf**
Close https://github.com/searxng/searxng-docker/issues/16

### CODE REVIEW

**Review by mrpaulblack — CHANGES_REQUESTED** [review]
Can you please also update the last part of the readme?

There are some references to the scripts:
```markdown
## Custom docker-compose.yaml
Do not modify docker-compose.yaml otherwise you won't be able to update easily from the git repository.
It is possible to use the [extend feature](https://docs.docker.com/compose/extends/) of docker-compose:
- stop the service: ```systemctl stop searxng-docker.service```
- create a new docker-compose-extend.yaml, check with ```start.sh```
- update searxng-docker.service (see SEARXNG_DOCKERCOMPOSEFILE)
- restart the service: ```systemctl restart searxng-docker.service```
## Multi Architecture Docker images
Supported architecture:
- amd64
- arm64
- arm/v7
## How to update ?
Check the content of [```update.sh```](https://github.com/searxng/searxng-docker/blob/master/update.sh)
```

**Comment by dalf** [comment]
@mrpaulblack see commit [d4ae67a](https://github.com/searxng/searxng-docker/pull/17/commits/d4ae67a468e93f8c36ef39e06a58076793606804)

**Review by mrpaulblack — APPROVED** [review]
I added another commit on top updating the readme... from my side LGTM :+1: 

@dalf please do a quick review when you have time and merge if you think the PR is ready; Thanks :D

**Comment by dalf** [comment]
thank you

**Pull request merged**
