### PR TITLE
Replace morty & filtron by redis & the limiter plugin

### LINKED ISSUE #3: rules.json : allow /image_proxy
`/image_proxy` can replaced Morty even on a public instance.

`rules.json` should not block the requests to this URL, or at least differently.

For reference https://github.com/paulgoio/searxng/blob/main/src/rules.json

### PR DESCRIPTION
**Pull request by dalf**
The current 
* [x] update README.md
* [x] use searxng/settings.yml
* [x] https://github.com/searxng/searxng/pull/990

What could be done:
* [ ] https://github.com/searxng/searxng/issues/965 (the issue exists before this PR).
* [ ] move the HTTP headers to searxng

---

Close  #3

### CODE REVIEW

**Comment by mrpaulblack** [comment]
@dalf After reading https://github.com/searxng/searxng-docker/issues/13 maybe its a good idea to not mount the entire conf directory with `uwsgi.ini`, `settings.yml` and `settings.yml.new`, but rather only the `settings.yml` file itself. Most people dont need to change anything in the `uwsgi.ini` file and if we dont mount it on the host it is easier for us to maintain and update the file. Same with `settings.yml`: We dont need an upgrade path if we only mount the changed settings from default config. Users can just go in and make the changes to the file themselves...

**Comment by dalf** [comment]
Alternative: we don't copy `uwsgi.ini` to the searxng volume and only rely on `/usr/local/searxng/dockerfiles/uwsgi.ini`.

There is one use case where the admin wants to change `uwsgi.ini` : each worker eats about 512MB of memory. In low memory environment, the reliable solution is to use 1 worker (by default there are as many workers as there are cores).

---

*if* we make a breaking change in the `searxng/searxng` docker image.

Actually, the searxng volume is not really docker friendly:
* either the settings.yml is not updated --> the admin could mount `/etc/searxng/settings.yml` without all this code: https://github.com/searxng/searxng/blob/b14ed494fb70f976cd77c47d27f29e6fb0bac670/dockerfiles/docker-entrypoint.sh#L96-L130
* either the settings.yml are erased --> there is no need to mount the volume.

Since there is `use_default_settings: true` ( see https://docs.searxng.org/admin/engines/settings.html#use-default-settings ), I suggest to rely on:
* `/etc/searxng/settings.yml`  (with or without `use_default_settings: true`). Not by default: the app uses the default one from the git repository.
* `/etc/uwsgi/uwsgi.ini`: `Dockerfile` copies `/usr/local/searxng/dockerfiles/uwsgi.ini` to `/etc/uwsgi/uwsgi.ini`.

Both can be mounted and replaced by the admin.

One possible way to deal with that, is to publish two docker images for a time.
* `latest`  as it is now
* `??-latest` : the new version. `??` to be defined.

I'm not sure this is a good solution since it breaks the current versioning ( `YYYY.MM.DD-hash` )

**Comment by mrpaulblack** [comment]
```
tmpfs:
      - /var/lib/redis
```
Does this on the redis container make sure that the redis data survives a redis container update? (Since otherwise the setup can break when redis gets updated and the container replaced, while SearXNG contaienr stays the same with the limter plugin...)

**Comment by dalf** [comment]
> enable hash plugin in settings.yml in this repo since its disabled upstream (https://github.com/searxng/searxng/pull/995)

done

> Does this on the redis container make sure that the redis data survives a redis container update? 

done = that's mean the IP of the user are stored on the disk (not in clear text, the hmac-sha256, since the secret key is stored too, that's mean the IPv4 are nearly in clear text).

Is it really what we want?

**Comment by dalf** [comment]
ping @mrpaulblack

**Review by mrpaulblack — APPROVED** [review]
LGTM :+1: (sorry for the really long review time -_- )

I tested this with an ubuntu server and everything works (after setting SEARXNG_HOSTNAME in .env file as well as the secret key in the settings.yml file)

This is a great first step :tada: ; next I think we should remove the helper scripts like start.sh, stop.sh and so on

I leave the merge up to you @dalf :+1:

**Comment by mrpaulblack** [comment]
Wait can you please revert https://github.com/searxng/searxng-docker/pull/12/commits/2518d247f9addd8e37089535c3b29a2333c778fe ? I think we both misunderstood I think your solution like that is better:
```
tmpfs:
      - /var/lib/redis
```

**Comment by dalf** [comment]
I have remove https://github.com/searxng/searxng-docker/commit/2518d247f9addd8e37089535c3b29a2333c778fe

**Review by mrpaulblack — APPROVED** [review]
LGTM; Thanks :D

This is a big step for our new stack impl. :tada:

**Pull request merged**
