### PR TITLE
Replace with official Valkey image

### PR DESCRIPTION
**Pull request by inetol**
Discussion #230

### CODE REVIEW

**Comment by inetol** [comment]
I can't get the database moved from one image to another, must be an issue with [docker-entrypoint.sh](https://github.com/valkey-io/valkey-container/blob/mainline/docker-entrypoint.sh) as I can't change the user on which the server is running either

**Comment by inetol** [comment]
WDYM? If we create another volume, Valkey will create a clean RDB losing all the botdetection data (again).

Although, I am of the opinion that docker-compose files is offered as a blueprint and should only be used for the initial installation and not updated from remote (at least not without checking the changes and taking the plunge if there is a big change). Images or config changes happen and there is not always the possibility of a clean migration without manual intervention, and more so in different configurations on different machines in different container managers.

**Comment by unixfox** [comment]
> WDYM? If we create another volume, Valkey will create a clean RDB losing all the botdetection data (again).

It's ok, if we wait too much time it's going to be an issue. But there has been only one week since the last change about valkey.

> Although, I am of the opinion that docker-compose files is offered as a blueprint and should only be used for the initial installation and not updated from remote (at least not without checking the changes and taking the plunge if there is a big change). Images or config changes happen and there is not always the possibility of a clean migration without manual intervention, and more so in different configurations on different machines in different container managers.

I would like to keep updates as smooth as possible when there is a possibility to do it.

**Comment by inetol** [comment]
OK, I've been a bit busy these days hence my delay.

Basically this PR is ready to go unless you want to rename the volume so that there are no conflicts with people who update the template *in a rough way*, in that case I don't know if `valkey-data2` would be good enough?

**Comment by unixfox** [comment]
Good for me yes :)

**Pull request merged**
