### PR TITLE
Enable limiter by default

### PR DESCRIPTION
**Pull request by dalf**
See https://github.com/searxng/searxng/pull/2832

### CODE REVIEW

**Comment by unixfox** [comment]
For `limiter.toml`, can't we just have this content:
```
[botdetection.ip_limit]

link_token = true
```

?

This way we do not touch the default settings.

**Comment by dalf** [comment]
nope : this works only for settings.yml

**Comment by unixfox** [comment]
Hum that's a huge bummer, wasn't that one of the benefit of using toml that you said @return42?

We would like to override values like `ipv4_prefix` or `ipv6_prefix` in the future.

**Comment by return42** [comment]
> nope : this works only for settings.yml

Thats not true, I implemented https://github.com/searxng/searxng/blob/master/searx/tools/config.py  with this config class the defaults are read from the schema file and updated by the /etc/searxng/limiter.toml file .. see https://github.com/searxng/searxng/blob/71358e9c673247e16125dc32b70f2553c469d814/searx/botdetection/limiter.py#L70-L85

**Comment by unixfox** [comment]
My memory is not failing, thank you @return42.

@dalf could you update the limiter.toml? thank you

**Comment by dalf** [comment]
Done, at least I hope so.
The `searx.tools` and `searx.botlimiter` aka limiter are unknown to me.

**Review by return42 — APPROVED** [review]

**Comment by unixfox** [comment]
The only issue here is that this will require people to `git pull` then `docker compose up` for this new change to be effective.

**Review by unixfox — APPROVED** [review]

**Comment by unixfox** [comment]
Just tested on:
- https://search.im-in.space/
- https://searx.headpat.exchange/

works really great

**Pull request merged**
