### PR TITLE
Include missing uwsgi.ini

### LINKED ISSUE #115: cp: can't create '/etc/searxng/uwsgi.ini': Permission denied
I followed the README.md.

output of docker compose up:

searxng  | SearXNG version 2023.01.20+316fcd5e
searxng  | Create /etc/searxng/uwsgi.ini
searxng  | cp: can't create '/etc/searxng/uwsgi.ini': Permission denied
searxng  | sed: /etc/searxng/uwsgi.ini: No such file or directory
searxng  | Use existing /etc/searxng/settings.yml
searxng  | Listen on 0.0.0.0:8080
searxng  | realpath() of /etc/searxng/uwsgi.ini failed: No such file or directory [core/utils.c line 3662]
searxng exited with code 1

What can i do about it?

UPDATE: I just run commands with superuser permissions, It fixed.

### PR DESCRIPTION
**Pull request by impaktor**
There is probably a reason why this file is in the gitignore, and not included in the source tree, but I'm opening this PR to start discussion on proper fix, as the docker compose doesn't work without it.

Possible fixes:
1. Accept this PR and merge
2. Add the file to project's root directory (or elsewhere) and update README that the file should be copied into proper location

This fixes #115

### CODE REVIEW

**Comment by inetol** [comment]
These files *should* be created when you start the SearXNG container and not included in this repository.

You can try changing the local path of the volume to a folder inside the home folder of the user running the container so that it has the necessary permissions, like so:

```console
volumes:
    - ./searxng:/home/myuser/searxng:rw
```

**Comment by AlyoshaVasilieva** [comment]
`chown -R root:root searxng-docker` (or whatever dir you have it in)

SearXNG docker only works properly if every file is owned by root for some reason. If you follow the repo instructions closely and put it inside `/usr/local` you likely already did this since normal users can't write there, at least on Debian.

**Comment by ppfeufer** [comment]
> SearXNG docker only works properly if every file is owned by root for some reason.

That is not correct at all
image

Your user just needs to be in the `docker` group …
And yes, the `uwsgi.ini` file is created.

**Comment by AlyoshaVasilieva** [comment]
I don't put my user in docker group. Is it an expected part of Docker installs?

**Comment by ppfeufer** [comment]
Make sure you have this in your `docker-compose.yml` file for the `searxng` section.

```yaml
    volumes:
      - ./searxng:/etc/searxng:rw
```
(https://github.com/searxng/searxng-docker/blob/master/docker-compose.yaml#L55-L56)

This will create a `searxng` directory in your docker directory and map `/etc/searxng` from inside the `searxng` container to it. This should include the `uwsgi.ini` file.

If in doubt and you already have that directory, stop your containers, rename that directory and start your containers again. That way it should re-create the directory and put all the files in it. You can then copy the settings from the renamed directory in there and restart the whole show, so you won't lose any settings or the like.

**Comment by impaktor** [comment]
- Regarding what to put in my docker-compose.yaml file: I use what is in current master. The volume line does indeed end in `:rw`.
- Regarding user group: yes, I'm in the docker user group (I'm using docker for other things as well). 
- If I `chown root:root -R` and remove the uwsgi.ini file, then (and only then) is the file re-generated (on Arch Linux).

> SearXNG docker only works properly if every file is owned by root for some reason. If you follow the repo instructions closely and put it inside /usr/local you likely already did this since normal users can't write there, at least on Debian.

Looking at the README I'd venture it's highly implicit that the folder must be root, as anyone following the README, will get an error when running `git clone on /usr/local` as they're likely not defaulting to being root in their terminals. They will then either `git clone` into whatever folder they already have in /home where they usually put all their git cloned repos, _or_ they will go full John Wayne and "sudo git clone" right there in /usr/local, which to me feels unnatural, which is why I opted for putting it in my home dir. 

## way forward
Either way, I'd argue some change is needed. E.g. explicitly add the `chown root:rotot -R` command, to indicate where ever the user puts it, this repo should run as root, or include the uwsgi file, or some other change?

**Comment by ppfeufer** [comment]
Or installing it in `/usr/local` is wrong in the first place. At least I can't find a good reason to have it there.
I installed it in my user's home directory and didn't have to `chown` anything.

**Comment by Bnyro** [comment]
This is probably not a good idea because the UWSGI config is updated dynamically based on environment variables (e.g. different amount of workers / threads), which would no longer work then.

**Pull request closed without merging**
