### PR TITLE
[fix] remove form-action 'self' from CSP header (Caddy)

### PR DESCRIPTION
**Pull request by return42**
Closes: https://github.com/searxng/searxng-docker/issues/177

### CODE REVIEW

**Comment by dalf** [comment]
The CSP is safety belt to make sure the user query is not sent to a third party: I prefer to keep it and implement https://github.com/searxng/searxng/issues/140

**Comment by mrpaulblack** [comment]
I agree with alex :+1:

**Comment by return42** [comment]
Yes, https://github.com/searxng/searxng/issues/140 is a much better solution ... this PR can only be a workaround for an intermediate solution ... @dalf it's up to you, if you think we better should not merge such a workaround, please close this PR. Since I don't use docker myself this should only be a suggestion / For me it would be fully OK to close the PR.

**Comment by dalf** [comment]
I prefer to implement the double redirect as described by @sevmonster and keep the CSP header as it is.

The issue is not about Docker: the CSP header should be set in all SearXNG instances. Also, the installation scripts should set them in the same way ( = not third party can received the query).

**Pull request closed without merging**
