### PR TITLE
README - link to https://github.com/searxng/filtron

### PR DESCRIPTION
**Pull request by return42**
This PR only modifies the README / I don't know how to update docker image https://hub.docker.com/r/dalf/filtron to use https://github.com/searxng/filtron

### CODE REVIEW

**Comment by return42** [comment]
@dalf I do not have rights to approve & merge / would you have a look at this PR / same with PR https://github.com/searxng/searxng-docker/pull/5

**Comment by dalf** [comment]
First I would like to setup some GitHub action to build & push the searxng/filtron image from the source.

**Comment by lavinj87** [comment]
The `dalf/filtron` image is preventing this app to be run with a raspberry:

```ubuntu@ubuntu:~/docker/searxng$ docker logs -f filtron
standard_init_linux.go:228: exec user process caused: exec format error
```

Can the `searxng/filtron` image be published so that this proyect can be deployed on a pi? 

Thanks!

**Comment by mrpaulblack** [comment]
Not needed anymore since filtron is not part of the SearXNG docker-compose stack anymore :+1: ; Closing.

**Pull request closed without merging**
